# Generated by Django 2.2.4 on 2019-08-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_uname', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('yieldd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromm', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=1000)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_password', models.CharField(max_length=100)),
                ('e_uname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=1000)),
                ('grain', models.CharField(max_length=100)),
                ('pic_url', models.CharField(max_length=100)),
            ],
        ),
    ]
